# Site settings
title: Bandavala
email: chandviki@outlook.com
description: "Collection of personal finance calculators and investment notes"
baseurl: ""
url: "http://yourdomain.com"
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
