# Site settings
title: Bandavala
email: chandviki@outlook.com
description: "Collection of personal finance calculators and investment notes"
url: "http://bandavala.github.io/"
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
